### ISSUE TITLE
Inconsistent documentation 

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/tweakwcs#24] opened 2018-12-07 15:02 UTC
The documentation for ``tweakwcs.imalign.tweak_wcs`` does not contain any mention of ``nmatches``, which is described in the parameters section for ``class tweakwcs.wcsimage.WCSGroupCatalog``.  Although very minor, it would definitely cause confusion for anyone trying to use this code.

**Comment by mcara** [comment] 2018-12-11 02:52
@stsci-hack That is because `tweak_wcs()` does not match catalogs. You have to do it yourself _before_ calling `tweak_wcs()`. I have added the following note to the documentation:

```
    .. note::
        Both reference and image catalogs must have been matched *prior to*
        calling ``tweak_wcs()``. This means that the lengths of both
        ``refcat`` and ``imcat`` catalogs must be equal *and* that coordinates
        with the same indices in both catalogs correspond to the same source.
```
This will be in a PR to be submitted soon.

**Comment by mcara** [comment] 2018-12-11 02:56
Unlike the "do-it-all", convenience function `tweak_image_wcs()` that also _matches_ catalogs, the "lower-level" `tweak_wcs` was designed to take care only of finding the linear transformation needed to correct the WCS and apply it to the mis-aligned WCS. Nothing more. Source finding and matching is left to the caller of `tweak_wcs()`.

**Closed** 2018-12-11 21:53 UTC
Labels: documentation
