### ISSUE TITLE
Fit performed backwards in wcsimage

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/tweakwcs#35] opened 2018-12-20 16:29 UTC
The call to 'iter_linear_fit()' on line 806 of 'wcsimage.py' has the first 2 arguments as:
``        fit = iter_linear_fit(
            refxy, im_xyref, xyindx=ref_idx, uvindx=minput_idx,
            fitgeom=fitgeom, nclip=nclip, sigma=sigma, center=(0, 0)
        )
<code deleted>
        xy_fit = fit['resids'] + fit['offset'] + np.dot(fit['uv_coords'],
                                                        fit['fit_matrix'])
``
with the reference catalog as the first argument and the image catalog as the second argument.  However, that function defines the inputs as:
``
def iter_linear_fit(xy, uv, xyindx=None, uvindx=None, xyorig=None, uvorig=None,
                    fitgeom='general', nclip=3, sigma=3.0, center=None):
<code deleted>

def fit_general(xy, uv):
<code deleted>
    # Return the shift, rotation, and scale changes
    result = build_fit(P, Q, 'general')
    resids = xy - np.dot(uv, result['fit_matrix']) - result['offset']
    result['resids'] = resids

    return result
``
Unfortunately, ``xy`` is treated as the image coordinates with ``uv`` treated as the reference coordinates in the fitting functions, just the opposite of what is being passed in by ``wcsimage``.  As a result, the changes made in PR #34 returns (effectively) the RA/Dec (as ``fit_RA`` and ``fit_DEC``) NOT of the image coordinates, but of the reference positions.

**Comment by stsci-hack** [comment] 2018-12-20 17:22
As we discussed, the real solution will be to remove the 'resids' component from the computation of 'xy_fit' in 'wcsimage.py'.

**Comment by mcara** [comment] 2018-12-20 17:24
I can't follow all this discussion above, but as discussed offline the issue is not related to the role of `xy` or `uv` but rather to the addition of `fit['resids']` which is not necessary and should be removed from the formula. It will be done in the next PR.

**Comment by mcara** [comment] 2018-12-24 06:39
Fixed via #36

**Closed by mcara** 2018-12-24 06:39 UTC
Labels: bug
